### ISSUE TITLE
Update to Hysteria v2.0.3

### ISSUE THREAD

**Issue by tobyxdd** [LorenEteval/hysteria2-python#1]
v2.0.3 fixed an important issue with the behavior of BBR congestion control so that it no longer erroneously sends packets much faster than the connection's capable of.

**Comment by tobyxdd** [comment]
Actually you can upgrade to v2.0.4 now... just released today 🗿

**Comment by LorenEteval** [comment]
> Actually you can upgrade to v2.0.4 now... just released today 🗿

Done. It will be bundled in next Furious release.

**Comment by LorenEteval** [comment]
Bundled in [Furious 0.2.9](https://github.com/LorenEteval/Furious/releases/tag/0.2.9).
